format = """
[â”Œâ”€](fg:#89b4fa)\
$os\
$sudo\
$username\
$directory\
\n[â””â”€](fg:#89b4fa) \
$git_branch\
$git_state\
$git_status\
$git_commit\
$nodejs\
$rust\
$python\
$golang\
$php\
$java\
$package\
"""

right_format = """
$battery\
$status\
$cmd_duration\
"""

add_newline = true

[username]
style_user = 'fg:#8AB4FB'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname$ssh_symbol](fg:#8AB4FB) '
trim_at = '.companyname.com'
disabled = false
ssh_symbol = ' î®©'

[directory]
style = "fg:#cba6f7"
format = " in [$path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï‰ "
"Music" = "ó°¸ª "
"Pictures" = "ï€¾  "

[git_branch]
symbol = "îœ¥"
format = '[[$symbol $branch ](fg:#769ff0)]($style)'

[git_commit]
tag_disabled = false
only_detached = true
tag_symbol = '\uf412 '
format = '[\($hash$tag\)]($style) '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
merge = '[\ue727 MERGING](bold red)'
rebase = '[\ue728 REBASING](bold red)'
revert = '[\uf0e2 REVERTING](bold red)'
cherry_pick = '[\ue29b PICKING](bold red)'

[git_status]
windows_starship = '/mnt/c/Users/username/scoop/apps/starship/current/starship.exe'

[nodejs]
symbol = "îœ˜"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = "î¨"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = "î˜§"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = "î˜ˆ"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[java]
symbol = "îœ¸"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[python]
symbol = "î˜†"
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[time]
disabled = false
time_format = "%A %T" # Monday Hour:Minute Format
format = '[[ ïº $time ](fg:#a0a9cb)]($style)'

[sudo]
style = 'bold yellow'
symbol = 'ïƒ§'
disabled = false
format = ' [as $symbol ]($style)'

[status]
style = 'bold blue'
symbol = 'âœ—'
success_symbol = 'ï®'
not_executable_symbol = '!'
not_found_symbol = '?'
sigint_symbol = 'âœ—'
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false

[os]
format = "[$symbol ]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Windows = " î˜ª"
Macos = " ï…¹"
Fedora = "î½†"

[cmd_duration]
min_time = 10
format = ' in [$duration](bold yellow)'

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "ó°¹"
charging_symbol = "[â†‘](italic bold green)"
discharging_symbol = "â†“"
unknown_symbol = "â–‘"
empty_symbol = "ó°º"

[package]
format = 'via [ğŸ $version](208 bold) '
disabled = false
